const locations = [
    {
        "Location_ID": 1,
        "Location_Name": "Godstow Abbey",
        "Location_Type": "Landmark",
        "Book": "His Dark Materials",
        "Trail_Number": 2,
        "Description": "Founded in 1133, is a historic ruin located near the River Thames in Oxford. The abbey's remnants offer a glimpse into medieval monastic life and are open to the public for exploration.<br><strong>Points of Interest</strong><ul><li>Ruins to Explore:<br>Visitors can wander through the remaining strucutres of the abbey church, cloister and surrounding buildings</li><li>Thames Path and Towpath:<br> A footpath, part of the long distance Thames Path and towpath lie to the east of the nunnery, offering a scenic walking and bike routes.</li></ul>",
        "Website": null,
        "Image": "https://upload.wikimedia.org/wikipedia/commons/4/41/Inside_Godstow_Nunnery_Ruins_-_geograph.org.uk_-_901076.jpg",
        "Book_Link": "In Philip Pullman's 'His Dark Materials,' Godstow Abbey is where the nuns cared for Lyra as a baby, highlighting its significance in her early life.",
        "Opening_Hours": "24/7",
        "Price": "Free",
        "Extra_Info": "<ul><li>Parking available at Port Meadow</li></ul>",
        "Address":"Godstow Rd, Oxford OX2 8PJ",
        "Average_Rating":"★★★★☆"
    },
    {
        "Location_ID": 2,
        "Location_Name": "The Trout Inn",
        "Location_Type": "Resturant",
        "Book": "His Dark Materials",
        "Trail_Number": 3,
        "Description": "Trout Inn is a historic riverside pub located on the banks of the River Thames in Oxford. Known for its picturesque views and traditional British cuisine, it has been a popular spot for locals and visitors alike.",
        "Website": "https://www.thetroutoxford.co.uk/#/",
        "Image": "https://live.staticflickr.com/2742/4517613329_9e212ef01b_b.jpg",
        "Book_Link": "The Trout Inn is featured in 'His Dark Materials' as a place frequented by characters. It was an old, stone inn outside Oxford in Lyra's world located on the River Thames.",
        "Opening_Hours": "Mon–Sat: 12:00–23:00, Sun: 12:00–21:30",
        "Price": "££",
        "Extra_Info": null,
        "Address":"",
        "Average Rating":"★★★★☆"
    },
    {
        "Location_ID": 3,
        "Location_Name": "Port Meadow",
        "Location_Type": "Landmark",
        "Book": "His Dark Materials",
        "Trail_Number": 1,
        "Description": "Port Meadow is an ancient area of common land in Oxford, offering expansive open space along the River Thames. It's known for its natural beauty, grazing horses and cattle, and is a popular spot for walking and picnics.",
        "Website": "",
        "Image": "https://doghikes.uk/wp-content/uploads/2023/04/IMG_8143-1024x768.jpeg",
        "Book_Link": "In 'His Dark Materials,' Port Meadow is depicted as a significant location where key events unfold, reflecting its real-world prominence in Oxford.",
        "Opening_Hours": "24/7",
        "Price": "Free",
        "Extra_Info": null,
        "Address":"",
        "Average Rating":"★★★★★"
    },
    {
        "Location_ID":4,
        "Location_Name":"Alice's Shop",
        "Location_Type":"Activity",
        "Book":"Alice in Wonderland",
        "Trail_Number": 4,
        "Description":"Alice's shop is a charming store located opposite Christ Church College. It inspired the 'old sheep shop' which was featured in Through the Looking-Glass. Offering a wide range of whimsical Alice in Wonderland themed gifts, souvenirs and collectibles, you wouldn't want to miss out on this cosy boutique. ",
        "Website":"https://aliceinwonderlandshop.com/",
        "Image":"https://www.silverscreen.tours/wp-content/uploads/2020/06/alices-shop-oxford-6972.jpg",
        "Book_Link":"This was a sweet shop that Alice Liddell, the inspiration for Alice, visited frequently. It became the inspiration for the Old Sheep Shop in Through the Looking Glass and is now a themed gift shop. The little shop also appeared in an illustration in Through the Looking-Glass.",
        "Opening_Hours":"10:00am - 18:00pm",
        "Price":"££",
        "Extra_Info":"<ul><li>Phone Number: 07500864135</li></ul>",
        "Address":"83 St Aldates, Oxford OX1 1RA",
        "Average Rating":"★★★★☆"
    },
    {
        "Location_ID": 5,
        "Location_Name": "Bodleian Library",
        "Location_Type": "Activity",
        "Book": "His Dark Materials",
        "Trail_Number": 4,
        "Description": "The Bodleian Library is one of the oldest libraries in Europe, serving as the main research library of the University of Oxford. It's celebrated for its historic architecture and vast collection of manuscripts and books.",
        "Website": "https://www.bodleian.ox.ac.uk/home",
        "Image": "https://cdn.prod.website-files.com/6703c45d648fece612410ecf/6728c808eaae847eaf9eb8eb_IMG_0395_76997e7570.webp",
        "Book_Link": "In 'His Dark Materials,' the Bodleian Library is portrayed as 'Bodley's Library,' where crucial information is sought, emphasizing its role as a center of knowledge.",
        "Opening_Hours": "Mon–Fri: 10:00–17:00, Sat: 10:00–17:00",
        "Price": "££",
        "Extra_Info": null,
        "Address":"",
        "Average Rating":"★★★☆☆"
    },
    {
        "Location_ID":6,
        "Location_Name":"Blenheim Palace",
        "Location_Type":"Landmark",
        "Book":"The Secret Garden",
        "Trail_Number": 1,
        "Description": "Blenheim Palace is a country house in Woodstock, Oxfordshire. It makes for a beautiful day out and offers a wide range of events throughout the year.<br><strong>Ticket Price</strong><br>Adults: £41.00<br>Children: £24.00<br>Families: £110.00<br>Tickets allow for year-round access to the palace.",
        "Website":"https://www.blenheimpalace.com/",
        "Image":"https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,f_jpg,h_822,q_75,w_1220/https://swtdmsmedia.newmindmedia.com/wsimgs/blenheim_palace_bladon_bridge_4__1211334718.jpg",
        "Book_Link":"Blenheim Palace was a filming location for the 2020 and 1993 versions of The Secret Garden movie.\nIn the 2020 version, the formal gardens appear including the rose gardens and water terraces. In the 1993 version, the palace and its grounds appear in several scenes.",
        "Opening_Hours":"10:00am - 16:30pm",
        "Price":"£££",
        "Extra_Info":null,
        "Address":"Woodstock, OX20 1PS",
        "Average_Rating":"★★★☆☆"
    },
    {
        "Location_ID": 7,
        "Location_Name": "Covered Market",
        "Location_Type": "Activity",
        "Book": "His Dark Materials",
        "Trail_Number": null,
        "Description": "The Covered Market in Oxford is a historic market with a diverse range of independent shops, boutiques, and eateries, offering a unique shopping experience.",
        "Website": "https://oxford-coveredmarket.co.uk/",
        "Image": "https://cdn.rt.emap.com/wp-content/uploads/sites/4/2024/04/01234550/Covered-Market-Oxford-Image-by-AIZAT-K-Shutterstock.jpg",
        "Book_Link": "The Covered Market was a market in Oxford in Lyra's world and sold fish. When Jessie Reynolds went missing, the market was searched.",
        "Opening_Hours": "Mon–Sat: 08:00–17:30, Sun: 10:00–16:00",
        "Price": "£",
        "Extra_Info":null,
        "Address":"",
        "Average Rating":"★★★☆☆"
    },
    {
        "Location_ID": 8,
        "Location_Name": "Botanical garden",
        "Location_Type": "Activity",
        "Book": "His Dark Materials",
        "Trail_Number": null,
        "Description": "hi",
        "Website": "https://www.obga.ox.ac.uk/",
        "Image": "https://www.experienceoxfordshire.org/wp-content/uploads/2017/06/132773933_5538028679556730_1384057612094066097_n.jpg",
        "Book_Link": "Features the bench where characters Will and Lyra meet; includes a sculpture depicting daemons from the series",
        "Opening_Hours": "10:00–17:00",
        "Price": "££",
        "Extra_Info":null,
        "Address":"",
        "Average Rating":"★★★★☆"
    },
    {
    "Location_ID":9,
    "Location_Name":"Christ Church College",
    "Location_Type":"Landmark",
    "Book":"Alice in Wonderland",
    "Trail_Number": 3,
    "Description":"One of Oxford's most iconic and grandest colleges, Christ Church is known for its stunning architecture and spacious quads. It has inspired countless visitors with its historic halls, breathtaking gardens and links to famous alumni. <br>You can enjoy the views of the exterior buildings and surrounding meadows for free however to explore inside, you need to book a guided tour through the college. There are various tours offered along with a wide range of events throughout the year.",
    "Website":"https://www.chch.ox.ac.uk/visit",
    "Image":"https://www.chch.ox.ac.uk/sites/default/files/styles/highlight_text_with_image_mobile/public/2023-08/tom-quad-highlight.jpg.webp?itok=10NJrXAa",
    "Book_Link":"This was the home of Alice Liddell, who was the inspiration for Alice. The dining hall here is thought to have inspired the Mad Hatter's Tea Party setting. The bells of Tom  Tower do not keep in time with the rest of Oxford's bells which encouraged the idea for the Mad Hatter's Tea party where it's always six o'clock.",
    "Opening_Hours":"10:00am - 4:15pm",
    "Price":"£",
    "Extra_Info":"<ul><li>Disabled Parking Available</li><li>Tours available in 13 different languages</li></ul>",
    "Address":"Christ Church, St Aldates, Oxford, OX1 1DP",
    "Average Rating":"★★★★★"
    },

    {
        "Location_ID": 10,
        "Location_Name": "Pitt Rivers Museum",
        "Location_Type": "Activity",
        "Book": "His Dark Materials",
        "Trail_Number": null,
        "Description": "The Pitt Rivers Museum houses an extensive collection of anthropological and archaeological artifacts from around the world. It's renowned for its unique display methods and diverse exhibits.",
        "Website": "https://www.prm.ox.ac.uk/",
        "Image": "https://theoxfordmagazine.com/wp-content/uploads/pitt-rivers-museum-and-museum-of-natural-history-to-reopen-on-22-september.jpg",
        "Book_Link": "A location Lyra visits in *The Subtle Knife*. Features props and costumes from the 'His Dark Materials' series, including the amber spyglass.",
        "Opening_Hours": "Tue–Sun: 10:00–17:00",
        "Price": "Free",
        "Extra_Info": null,
        "Address":"",
        "Average Rating":"★★★★☆"
    },
    {
        "Location_ID":11,
        "Location_Name":"University Park- River Walk",
        "Location_Type":"Park",
        "Book":"Alice in Wonderland",
        "Trail_Number": 1,
        "Description":"hi",
        "Website":"",
        "Image":"https://www.experienceoxfordshire.org/wp-content/uploads/2017/03/University-Parks-.jpg",
        "Book_Link":"This was the home of Alice Liddell, who was the inspiration for Alice. The dining hall here is thought to have inspired the Mad Hatter's Tea Party setting.",
        "Opening_Hours":"",
        "Price":"",
        "Extra_Info":null,
        "Address":"",
        "Average Rating":"★★★★★"
    },
    {
        "Location_ID":12,
        "Location_Name":"St Mary's Passage",
        "Location_Type":"Landmark",
        "Book":"The Chronicles of Narnia",
        "Trail_Number": 1,
        "Description":"hi",
        "Website":"",
        "Image":"https://i0.wp.com/flyingscotsgirl.com/wp-content/uploads/2020/08/img_4641.jpg?resize=748%2C913&ssl=1",
        "Book_Link":"Narnia door and lamp post that inpsired the scene with Mr Tumnus.",
        "Opening_Hours":"24/7",
        "Price":"Free",
        "Extra_Info":null,
        "Address":"",
        "Average Rating":"★★★☆☆"
    },
    {
        "Location_ID": 13,
        "Location_Name": "Exeter College",
        "Location_Type": "Landmark",
        "Book": "His Dark Materials",
        "Trail_Number": 5,
        "Description": "Exeter College, founded in 1314, is one of the constituent colleges of the University of Oxford. It features stunning architecture, including a Victorian Gothic chapel and beautiful gardens.",
        "Website": "https://www.exeter.ox.ac.uk/",
        "Image": "https://footprints-tours.com/wp-content/uploads/2018/12/Exeter-College-Quad.jpg",
        "Book_Link": "Exeter College's rich history and architectural beauty contribute to the atmospheric setting reminiscent of scholarly pursuits depicted in 'His Dark Materials.'",
        "Opening_Hours": "Mon–Fri: 14:00–17:00, Sat–Sun: 13:00–17:00",
        "Price": "£",
        "Extra_Info": null,
        "Address":"",
        "Average Rating":"★★★★☆"
    },
    {
        "Location_ID":14,
        "Location_Name":"The Randolph Hotel",
        "Location_Type":"Restaurant",
        "Book":"Alice in Wonderland",
        "Trail_Number": 2,
        "Description":"<i>'Tumble down the rabbit hole and join us for tea!'</i><br>Attend a tea party with the Mad Hatter at The Randolph Hotel. Offering a wide range of Wonderland inspired food and cocktails, you wouldn't want to be late to this very important date. If a tea party isn't your dream location, this restaurant also hosts a wide range of events.",
        "Website":"https://www.thealiceoxford.com/",
        "Image":"https://dancinginhighheels.com/wp-content/uploads/2022/07/CE68605B-F034-4A6C-B99D-62E3FD51002A_1_201_a-1440x949.jpeg",
        "Book_Link":"The Alice Restaurant offers a wide range of Wonderland inpsired dishes and cocktails.",
        "Opening_Hours":"Restaurant and Bar: 12-9pm Alice in Wonderland Menu: 12-4pm",
        "Price":"££",
        "Extra_Info":"<ul><li>Booking Required</li><li>Vegan Menu</li><li>Gluten-Free Menu</li></ul>",
        "Address":"The Randolph Hotel, Beaumont Street, Oxford, OX1 2LN",
        "Average_Rating":"★★★★★"
    },
    {
        "Location_ID":15,
        "Location_Name":"Oxford Botanic Gardens",
        "Location_Type":"Landmark",
        "Book":"The Secret Garden",
        "Trail_Number": 2,
        "Description":"",
        "Website":"https://www.glam.ox.ac.uk/botanic-garden",
        "Image":"https://media.timeout.com/images/106268077/image.jpg",
        "Book_Link":"",
        "Opening_Hours":"10:00am - 16:00pm",
        "Price":"£",
        "Extra_Info":"",
        "Address":"Rose Ln, Oxford OX1 4AZ",
        "Average_Rating":"★★★★☆"
    },
    {
        "Location_ID":16,
        "Location_Name":"The Ornate Door",
        "Location_Type":"Landmark",
        "Book":"The Chronicles of Narnia",
        "Trail_Number": 2,
        "Description":"",
        "Website":null,
        "Image":"https://visitoxfordtours.com/wp-content/uploads/2023/07/narnia-in-oxford1.jpg.webp",
        "Book_Link":"",
        "Opening_Hours":"24/7",
        "Price":"Free",
        "Extra_Info":"",
        "Address":"",
        "Average_Rating":"★★☆☆☆"
    },
    {
        "Location_ID":17,
        "Location_Name":"Magdalen College Cloisters",
        "Location_Type":"Landmark",
        "Book":"The Chronicles of Narnia",
        "Trail_Number": 3,
        "Description":"<strong>Ticket Prices<ul><li>Adults: £10.00</li><li>Seniors: £9.00</li><li>Family Ticket: £28.00</li></ul></strong>",
        "Website":"https://www.magd.ox.ac.uk/visiting-magdalen-college/",
        "Image":"https://englandrover.com/wp-content/uploads/2018/10/magdalen-college-oxford-exterior.jpg",
        "Book_Link":"",
        "Opening_Hours":"10:00am - 17:00pm",
        "Price":"£",
        "Extra_Info":"",
        "Address":"",
        "Average_Rating":"★★★☆☆"
    },
    {
        "Location_ID":18,
        "Location_Name":"The Story Museum",
        "Location_Type":"Activity",
        "Book":"The Chronicles of Narnia",
        "Trail_Number": 4,
        "Description":"Walk through the pages as you step through the wardrobe and into the world created by C.S Lewis.",
        "Website":"https://www.storymuseum.org.uk/explore/the-enchanted-library",
        "Image":"https://storymuseum.s3-assets.com/_1023x682_crop_center-center_80_none/Narnia_credit_Diane_Auckland.jpg",
        "Book_Link":"While The Story Museum offers a range of exhibits we recommend losing yourself in the Chronicles of Narnia exhibition. Enter through the wardrobe into the magical land of Narnia.",
        "Opening_Hours":"10:00am - 16:30pm",
        "Price":"£",
        "Extra_Info":"<ul><li>Phone Number: 01865 790050</li></ul>",
        "Address":"42 Pembroke St, Oxford OX1 1BP",
        "Average_Rating":"★★★☆☆"
    }

]
